Feature: Support for ERC-721
LimeChain/hashport-contracts pull request #24
Opened 2021-11-18 11:25 UTC by failfmi

**Detailed description**:
* Be able to portal ERC-721 between networks
* Returning a wrapped ERC-721 would require to pay with an ERC-20 token, set by the owner

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-11-19 12:56 UTC, Daniel-K-Ivanov requested changes

2021-11-19 12:56 UTC, Daniel-K-Ivanov commented on contracts/facets/ERC721PortalFacet.sol
> +        emit BurnERC721(_targetChain, _wrappedToken, _tokenId, _receiver);
nit: Would we want to emit the `fee` as-well?

2021-11-19 12:56 UTC, Daniel-K-Ivanov commented on contracts/interfaces/IERC721PortalFacet.sol
> +        address receiver
I think that it would be useful for this parameter to be `indexed`

2021-11-19 12:56 UTC, Daniel-K-Ivanov commented on contracts/interfaces/IERC721PortalFacet.sol
> +        bytes receiver
I think that it would be useful for this parameter to be `indexed`

2021-11-19 12:56 UTC, Daniel-K-Ivanov commented on contracts/interfaces/IERC721PortalFacet.sol
> +    event WrappedTokenERC721Deployed(
This event is not used

2021-11-19 12:56 UTC, Daniel-K-Ivanov commented on contracts/facets/PaymentFacet.sol
> +    function updateMember(
I don't think that `updateMember` should be in this file since it has nothing to do with the `members` logic. Its place is with the Governance Facet. We can introduce `GovernanceFacetV2` that holds only the updated `updateMember` method

2021-11-19 12:56 UTC, Daniel-K-Ivanov commented on contracts/libraries/LibPayment.sol
> +    }
It seems to me that those 2 methods are the same as `tokensCount` and `tokenAt`

2021-11-19 12:58 UTC, failfmi commented on contracts/interfaces/IERC721PortalFacet.sol
> +        bytes receiver
In go-ethereum, you cannot get the receiver if it's indexed.

2021-11-19 12:58 UTC, failfmi commented on contracts/interfaces/IERC721PortalFacet.sol
> +        address receiver
In go-ethereum, you cannot get the receiver if it's indexed.

2021-11-22 13:56 UTC, Daniel-K-Ivanov commented on scripts/upgrade-erc721-support.js
> +  const diamondRemoveTx = await router.diamondCut(diamondRemoveCut, ethers.constants.AddressZero, "0x");
Replace instead of Remove + Add

2021-11-22 16:03 UTC, Daniel-K-Ivanov approved these changes

2021-11-23 07:01 UTC, Daniel-K-Ivanov requested changes

2021-11-23 07:01 UTC, Daniel-K-Ivanov commented on scripts/upgrade-erc721-support.js
> +  const diamondRemoveTx = await router.diamondCut(diamondRemoveCut, ethers.constants.AddressZero, "0x");
`diamondRemoveCut` is a leftover variable

2021-11-23 07:01 UTC, Daniel-K-Ivanov commented on scripts/upgrade-erc721-support.js
> +async function upgradeErc721Support(routerAddress) {
Normally it is better to verify contracts after all deployment finishes since sometimes etherscan fails with "missing contract" if you try to verify if right after deployment. It needs a couple of blocks to "recognise" the newly deployed contract

2021-11-23 07:03 UTC, failfmi commented on scripts/upgrade-erc721-support.js
> +async function upgradeErc721Support(routerAddress) {
Never experienced this

2021-11-23 07:29 UTC, Daniel-K-Ivanov approved these changes

2021-11-23 07:30 UTC, merged