Add slither static analysis to CI
LimeChain/hashport-contracts pull request #34
Opened 2022-09-07 05:09 UTC by julian-bcw

This pipeline should will help prevent potential security vulnerabilities in any future updates to the smart contracts.
Additionally, there is only one minor fix to make the existing code compliant. It fixes a loss of precision due to a divide-before-multiplication. See [here](https://github.com/crytic/slither/wiki/Detector-Documentation#divide-before-multiply) for reference. This specific instance is likely harmless, but it would be best to fix it so that we can leave the check in the pipeline for the future.

I have also disabled a number of "low severity" checks in this pipeline, that are unnecessary (such as style checks).

2022-09-07 10:59 UTC, failfmi requested changes

2022-09-07 10:59 UTC, failfmi commented on contracts/libraries/LibFeeCalculator.sol
> +        _fc.previousAccrued += diffAccrued;
Tests are failing. Please revisit the code and try to understand why this is implemented like this.

2022-09-08 04:32 UTC, julian-bcw commented on contracts/libraries/LibFeeCalculator.sol
> +        _fc.previousAccrued += diffAccrued;
Thanks, I have undone the change, and left a comment so the CI will ignore this alarm.

2022-09-08 10:47 UTC, failfmi approved these changes

2022-09-08 10:47 UTC, merged