Fee policies for legal entity
LimeChain/hashport-contracts pull request #37
Opened 2022-10-10 08:48 UTC by trayanm

Add EntityFeePolicyStore to handle token fee policies 
Add FeeCalculatorV2Facet to handle fee policies per user and token 
Add LibFeePolicy with storage
Update LibFeeCalculator.distributeRewards to check and use fee policies 
Add scrpts/fee-policy-management.js to handle fee policies management 
Update README.dm with fee policy scripts

Signed-off-by: Trayan Manolov <trayan.manolov@limechain.tech>

2022-10-10 23:39 UTC, failfmi reviewed
Can all the formatting changes be reverted?
Also, no tests are found in the PR.

2022-10-10 23:39 UTC, failfmi commented on contracts/facets/FeeCalculatorFacet.sol
> -        LibFeeCalculator.Storage storage fcs = LibFeeCalculator
The whole file has only formatting changes.

2022-10-10 23:39 UTC, failfmi commented on contracts/interfaces/IFeeCalculator.sol
> +    event Claim(address indexed member, address indexed memberAdmin, address token, uint256 amount);
The whole file has only formatting changes.

2022-10-10 23:52 UTC, failfmi commented on contracts/facets/FeeCalculatorV2Facet.sol
> +contract FeeCalculatorV2Facet is IFeeCalculatorV2 {
If you are adding new functions and not editing the functions of `FeeCalculatorFacet`, shouldn't the name of the contract be something related to fee policies?

2022-10-10 23:53 UTC, failfmi commented on scripts/fee-policy-management.js
> +    }];
Since you have made changes in `LibFeeCalculator`, you need to replace the existing facets (or only the methods) that use the previous version with the new one.

2022-10-10 23:58 UTC, failfmi commented on scripts/fee-policy-management.js
> +    Verification
`//`

2022-10-11 00:01 UTC, failfmi commented on README.md
> +Deployes a store contract to manage and calculate token fee policies
Deploys

2022-10-11 08:08 UTC, trayanm commented on contracts/facets/FeeCalculatorV2Facet.sol
> +contract FeeCalculatorV2Facet is IFeeCalculatorV2 {
FeeCalculatorV2Facet will be renamed to FeePolicyFacet, which implements IFeePolicyFacet

2022-10-14 11:03 UTC, failfmi reviewed
Why do you change the base branch to `feature/30_fees_per_user_policy`. The previous fee policy changes are useless.

2022-10-14 11:03 UTC, failfmi commented on test/router.js
> +        await expect(router.setPercentageFeeTokenPolicy(FeePolicyStore.address, testNativeToken2.address, 10)).to.not.be.reverted;
How are you sure that it actually set the token policy?

2022-10-14 11:03 UTC, failfmi commented on test/router.js
> +        await expect(router.setFlatFeeTokenPolicy(FeePolicyStore.address, testNativeToken1.address, 1000)).to.not.be.reverted;
How are you sure that it actually set the token policy?

2022-10-14 11:03 UTC, failfmi commented on test/router.js
> +        await expect(router.setTiersTokenPolicy(
How are you sure that it actually set something?

2022-10-14 11:03 UTC, failfmi commented on test/router.js
> +        )).to.not.be.reverted;
How are you sure that something has been set?

2022-10-14 11:03 UTC, failfmi commented on test/router.js
> +        await expect(router.removeFeePolicyToken(FeePolicyStore.address, testNativeToken1.address)).to.not.be.reverted;
DId it in fact, remove the fee policy?

2022-10-14 11:14 UTC, failfmi commented on contracts/EntityFeePolicyStore.sol
> +        if ((range.hasFrom == false || _amount >= range.amountFrom) && (range.hasTo == false || _amount < range.amountTo)) {
There is a static analysis error found:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/20928965/195833809-cd1ab055-f97a-4b2f-802a-5802c3639699.png">

2022-10-14 11:15 UTC, failfmi commented on contracts/EntityFeePolicyStore.sol
> +        if ((range.hasFrom == false || _amount >= range.amountFrom) && (range.hasTo == false || _amount < range.amountTo)) {
You can find the error [here](https://github.com/LimeChain/hashport-contracts/actions/runs/3248323420)

2022-10-14 11:50 UTC, trayanm commented on scripts/fee-policy-management.js
> +    }];
I want to merge with branch for epic branch, not main. As we may have to make changes in RouterFacet after the tasks in hashport-validator.

2022-10-14 11:59 UTC, trayanm commented on test/router.js
> +    xit('should remove all functions', async () => {
This test tries to remove "all" methods from the diamond instantiated by IRouterDiamond, including the fee policy methods. As the fee policy facet is an upgrade of the Router - FeePolicyFaced is not deployed at this point of the test. I will change the test logic - to have all the facets in the first `before` and I will make separate `describe` for Router upgrade.

2022-10-14 12:03 UTC, trayanm commented
The base branch is changed to the **epic** branch with name `681_fees_per_user_contracts` (which was the initial idea). We may have to make changes in RouterFacet after the tasks in hashport-validator.

2022-10-14 12:08 UTC, trayanm commented on test/router.js
> +        await expect(router.setTiersTokenPolicy(
Please confirm adding methods for extracting the fee policy data - like assigned users, tokens and/or fee policies.
We may not need such methods for production.

2022-10-14 12:13 UTC, trayanm commented on test/router.js
> +        await expect(router.setFlatFeeTokenPolicy(FeePolicyStore.address, testNativeToken1.address, 1000)).to.not.be.reverted;
test `should set flat token policy`- is testing setting the policy. Asserting the actual saved data requires making larger contract. Please confirm adding view methods for getting users, tokens and/or fee policies.
test `should calculate flat fee` -  is testing the calculation of flat fee

2022-10-14 12:31 UTC, trayanm commented on scripts/fee-policy-management.js
> +    }];
We are adding new library LibFeePolicy. The existing library LibFeeCalculator is using LibFeePolicy in method LibFeeCalculator.distributeRewards
The facets that are using LibFeeCalculator are:
ERC721PortalFacet.sol (existing)
FeeCalculatorFacet.sol (existing)
FeePolicyFacet.sol (new)
GovernanceFacet.sol (existing)
GovernanceV2Facet.sol (existing)
RouterFacet.sol (existing) - only here we are using LibFeeCalculator.distributeRewards

Please confirm the upgrade logic:
- upgrading all of the above facets
- upgrading only the RouterFacet

2022-10-14 13:35 UTC, julian-bcw commented on .github/workflows/slither.yml
> +          slither-args: "--exclude-low --exclude-informational --exclude-optimization --exclude unused-return,uninitialized-local-variables"
Looks like an accidental tab was added after reverting the slither version change

2022-10-14 13:37 UTC, julian-bcw commented on contracts/EntityFeePolicyStore.sol
> +pragma solidity 0.8.3;
Shouldn't we use the latest version of solidity (0.8.17)? Or would it break compatibility with existing smart contracts?

2022-10-24 14:57 UTC, rokn commented
We should update the deploy router script as well so new deploys include the new facet.

2022-10-24 14:57 UTC, rokn commented on contracts/interfaces/IRouterDiamond.sol
>  interface IRouterDiamond is
We should add IFeePolicyFacet here

2022-10-24 14:57 UTC, rokn commented on contracts/libraries/LibFeeCalculator.sol
> +    /// @param _user The target user
nit: Maybe a better wording:
```
    /// @notice Distributes service fee for a given transfer based on sender, token and amount transferred
    /// @dev Usual execution of the method is the lock operation.
    /// @param _user Transfer sender

2022-10-24 14:57 UTC, rokn commented on contracts/libraries/LibFeeCalculator.sol
> +        FeeCalculator storage fc = fcs.nativeTokenFeeCalculators[_token];
These aren't needed.

2022-10-24 14:57 UTC, rokn commented on contracts/libraries/LibFeePolicy.sol
> +    using EnumerableSet for EnumerableSet.AddressSet;
Leftover, same for line 11

2022-10-24 14:57 UTC, rokn commented on scripts/fee-policy-management.js
> +};
nit: no new line

2022-10-24 15:03 UTC, rokn commented on README.md
> +```
This should be updated

2022-10-25 09:10 UTC, trayanm commented on scripts/fee-policy-management.js
> +    }];
The upgrade script is changed to upgrade the router only with:
RouterFacet - action Replace
RouterFacetV2 - action Add
FeePolicyFacet - action Add

2022-10-25 10:02 UTC, rokn approved these changes

2022-10-25 10:43 UTC, failfmi commented on contracts/libraries/LibFeeCalculator.sol
> +   /// @notice Distributes service fee for a given transfer based on sender, token and amount transferred
nit: missing extra space

2022-10-25 10:43 UTC, failfmi commented on contracts/facets/RouterFacetV2.sol
> +contract RouterFacetV2 is IRouterV2 {
Given that most of the logic is the same for RouterFacet & RouterFacetV2, why are they separated? (The old RouterFacet will have to be replaced upon upgrade for sure).

2022-10-25 10:43 UTC, failfmi commented on contracts/facets/RouterFacetV2.sol
> +import "../WrappedToken.sol";
nit: unnecessary import

2022-10-25 10:43 UTC, failfmi commented on contracts/facets/RouterFacet.sol
>          uint256 serviceFee = LibFeeCalculator.distributeRewards(
I think you need to have the fee passed as parameter upon `lock` as well.

2022-10-25 10:43 UTC, failfmi commented on contracts/facets/RouterFacetV2.sol
> +    /// @param _calculatedFee Calculated fee by the validator
`@param _serviceFee The protocol service fee`

2022-10-25 10:43 UTC, failfmi commented on contracts/libraries/LibFeeCalculator.sol
> +                (calculatedFee, policyExists) = IFeePolicy(userFeePolicyAddress).feeAmountFor(_user, _token, _amount);
I am not sure what the final decision for `feeAmountFor` was.
Is it going to have 2 return arguments or only 1?
If so, isn't the idea of `policyExists` to have an `if` condition statement whether to use the calculated fee from the contract or to do the default calculation (with the fee set for the token in the Diamond)?

2022-10-25 14:37 UTC, trayanm commented on contracts/libraries/LibFeeCalculator.sol
> +                (calculatedFee, policyExists) = IFeePolicy(userFeePolicyAddress).feeAmountFor(_user, _token, _amount);
We no longer need the second field (bool exists) and it will be removed. We added a validation for calculated fee like:
```
if (_calculatedFee > 0 && _calculatedFee < serviceFee) {
    serviceFee = _calculatedFee;
}
```

2022-10-26 07:37 UTC, trayanm commented on contracts/facets/RouterFacetV2.sol
> +contract RouterFacetV2 is IRouterV2 {
As I tested - if we execute action Replace for Router.sol with the new param - there is an revert with message `"LibDiamondCut: Can't remove function that doesn't exist"`. This is because of the new function `unlockWithFee(...)`. That is why the steps for upgrade are: 
- Replace existing instance - with function `unlock(...)`
- Add RouterV2 with the new function - with function `unlockWithFee(...)`

2022-10-26 07:54 UTC, failfmi commented on contracts/facets/RouterFacetV2.sol
> +contract RouterFacetV2 is IRouterV2 {
You can only replace the old functions and in another argument only the addition with the new function(s).

2022-10-26 07:55 UTC, trayanm commented on contracts/libraries/LibFeeCalculator.sol
> +                (calculatedFee, policyExists) = IFeePolicy(userFeePolicyAddress).feeAmountFor(_user, _token, _amount);
In task [EVM-side fees per user when unlocking](https://github.com/LimeChain/hashport-validator/issues/684) which describes changes in function `unlock(...)`,  there is this [comment](https://github.com/LimeChain/hashport-validator/issues/684#issuecomment-1212784738):

- smart contract verifies that the fee provided is no more than the standard 0.5% fee

My assumption is that the same rule should apply for function `lock(...)`. With that - we have only one function to verify the above rule (for lock and unlock) and the same function is collects the tax. The existence of the policy is described with `_calculatedFee > 0`

2022-10-26 09:12 UTC, failfmi commented on contracts/facets/RouterFacetV2.sol
> +import "../WrappedToken.sol";
It is for "../WrappedToken.sol"

2022-10-26 09:15 UTC, failfmi commented on contracts/libraries/LibFeeCalculator.sol
> +                (calculatedFee, policyExists) = IFeePolicy(userFeePolicyAddress).feeAmountFor(_user, _token, _amount);
```solidity
        address userFeePolicyAddress = LibFeePolicy.feePolicyStoreAddress(
            _user
        );
        uint256 serviceFee;

        if (userFeePolicyAddress != address(0)) {
            serviceFee = IFeePolicy(userFeePolicyAddress).feeAmountFor(
                _user,
                _token,
                _amount
            );
        } else {
            serviceFee = (_amount * fc.serviceFeePercentage) / fcs.precision;
        }
        fc.feesAccrued = fc.feesAccrued + serviceFee;

        return serviceFee;
```

When you have `unlock` with externally signed fee, just accrue directly the fee.

2022-10-27 09:39 UTC, trayanm commented on contracts/libraries/LibFeeCalculator.sol
> +                (calculatedFee, policyExists) = IFeePolicy(userFeePolicyAddress).feeAmountFor(_user, _token, _amount);
the logic is reverted so that `IFeePolicy.feeAmountFor(...)` returns two params `(uint256 feeAmount, bool exist)`.
Also the function `LibFeeCalculator.distributeRewardsWithFee(...)` is split to 3 variants:

- `distributeRewards(address,uint256)` - default implementation. Used in `RouterFacet.unlock(...)`
- `distributeRewardsWithPolicy(uint256,address,address,uint256)` - upgraded functionality to calculate fee policy. Used in `RouterFacet.lock(...)`
- `distributeRewardsWithFee(address,uint256,uint256)` - new method with additional parameter for calculated fee. Used in `RouterFacet.unlockWithFee(...)`

Also - the actual calculation of serviceFee is outsourced to new function `calcServiceFee(uint256 _amount, uint256 _serviceFeePercentage, uint256 _precision)`. The goal is to have only one method, where this calculation is performed

2022-10-27 09:43 UTC, trayanm commented on contracts/facets/RouterFacetV2.sol
> +contract RouterFacetV2 is IRouterV2 {
Thank you for your advice. The logic is reverted so that and IRouterV2 is deleted. In the upgrade script - we are updating only the changed functions with:

```
const diamondCut = [
        { facetAddress: RouterFacet.address, action: enumFacetCutAction.Replace, functionSelectors: [RouterFacet.interface.getSighash('lock(uint256,address,uint256,bytes)')] },
        { facetAddress: RouterFacet.address, action: enumFacetCutAction.Replace, functionSelectors: [RouterFacet.interface.getSighash('unlock(uint256,bytes,address,uint256,address,bytes[])')] },
        { facetAddress: RouterFacet.address, action: enumFacetCutAction.Add, functionSelectors: [RouterFacet.interface.getSighash('unlockWithFee(uint256,bytes,address,uint256,address,uint256,bytes[])')] },
        { facetAddress: FeePolicyFacet.address, action: enumFacetCutAction.Add, functionSelectors: getSelectors(FeePolicyFacet) }
    ];
```

2022-10-27 11:42 UTC, failfmi commented on contracts/interfaces/IRouter.sol
> +        uint256 _calculatedFee,
uint256 _serviceFee

2022-10-27 11:42 UTC, failfmi commented on contracts/libraries/LibFeeCalculator.sol
> +    function  distributeRewardsWithPolicy(
nit: formatting

2022-10-27 11:42 UTC, failfmi commented on contracts/libraries/LibFeeCalculator.sol
> +        if (_user != address(0)) {
I think this case will always be hit, so the `if` is redundant.

2022-10-27 11:42 UTC, failfmi commented on contracts/libraries/LibFeeCalculator.sol
> +    function calcServiceFee(uint256 _amount, uint256 _serviceFeePercentage, uint256 _precision) internal pure returns(uint256) {
nit: formatting

2022-10-27 11:42 UTC, failfmi commented on contracts/facets/RouterFacet.sol
> +    /// @param _calculatedFee Calculated fee by the validator
@param _serviceFee The protocol service fee

2022-10-27 11:42 UTC, failfmi commented on contracts/facets/RouterFacet.sol
> +        uint256 _calculatedFee,
uint256 _serviceFee

2022-10-27 11:42 UTC, failfmi commented on contracts/libraries/LibFeeCalculator.sol
> +        }
If this requirement exists, we should at least document it in the function

2022-10-27 11:42 UTC, failfmi commented on contracts/libraries/LibFeePolicy.sol
> +            _localStorage.userStoreAddresses[_userAddress] = _feePolicyAddress;
nit: formatting

2022-10-27 11:42 UTC, failfmi commented on contracts/libraries/LibFeePolicy.sol
> +        LibFeePolicy.Storage storage _localStorage = feePolicyStorage();
You can rename the variable to fps (fee policy storage).

2022-11-02 09:43 UTC, failfmi commented on contracts/facets/RouterFacet.sol
> +        uint256 _serviceFee
Could we move it before `v`, `r`, and `s`?

2022-11-02 09:45 UTC, failfmi commented on contracts/facets/RouterFacet.sol
> +    /// @param _serviceFee Calculated service fee to be charged
Here as well

2022-11-03 07:34 UTC, failfmi reviewed
I think that not everything is covered with tests.
Execute `npm run coverage` and check whether the new functionality has been covered with tests, including `branches` section.

2022-11-03 07:34 UTC, failfmi commented on abi/ReplaceFacet.json
> +]
We do not need the abi for this here.

2022-11-03 07:34 UTC, failfmi commented on contracts/policies/FlatFeePerTokenPolicy.sol
> +contract FlatFeePerTokenPolicy is IFeePolicy, Ownable {
There are some unused variable warning upon compilation. Do not name them, so the warning does not show.

2022-11-03 07:34 UTC, failfmi commented on contracts/policies/FlatFeePolicy.sol
> +contract FlatFeePolicy is IFeePolicy, Ownable {
There are some unused variable warning upon compilation. Do not name them, so the warning does not show.

2022-11-03 07:34 UTC, failfmi commented on contracts/policies/PercentageFeePolicy.sol
> +contract PercentageFeePolicy is IFeePolicy, Ownable {
There are some unused variable warning upon compilation. Do not name them, so the warning does not show.

2022-11-03 07:34 UTC, failfmi commented on contracts/facets/FeePolicyFacet.sol
> +    }
Can't we merge the methods and just pass `address(0)` for `_feePolicyAddress` when removed?

2022-11-03 07:34 UTC, failfmi commented on contracts/facets/FeePolicyFacet.sol
> +}
I guess you do not need this.

2022-11-03 07:34 UTC, failfmi commented on contracts/facets/RouterFacet.sol
> +    }
Can we move this to `FeeCalculatorFacet`? Additional upgrade will be needed for that facet anyway

2022-11-03 07:34 UTC, failfmi commented on contracts/libraries/LibFeePolicy.sol
> +    /// @notice Adds array of user address to IFeePolicy
Sets fee policy for a given address

2022-11-03 07:34 UTC, failfmi commented on scripts/fee-policy-management.js
> +        { facetAddress: ethers.constants.AddressZero, action: enumFacetCutAction.Remove, functionSelectors: ['0xb258848a'] }, // lock(uint256,address,uint256,bytes)
Don't you have to remove the old `lockWithPermit` as well?
Plus, I would like the upgrade to be not only for the given functions, but the facets as a whole.
It will become really hard to maintain different versions of the libraries inside the facets (now it's not only the `GovernanceFacet`& `GovernanceV2Facet`, so a whole upgrade with the facets, which have the altered libraries would be best.

Example for RouterFacet:
* Execute remove for the whole facet. (you can call the diamond and fetch all the function selectors).
* Then, add the new `RouterFacet`.
* Apply this for all facets that have altered libraries

2022-11-03 07:39 UTC, failfmi commented on scripts/fee-policy-management.js
> +        { facetAddress: ethers.constants.AddressZero, action: enumFacetCutAction.Remove, functionSelectors: ['0xb258848a'] }, // lock(uint256,address,uint256,bytes)
Don't hardcode function selector, use `ethers` to generate it:
`ethers.utils.keccak256(ethers.utils.toUtf8Bytes('lock(...)'))` and get the first 4 bytes + `0x`

2022-11-04 06:42 UTC, failfmi commented on contracts/libraries/LibFeeCalculator.sol
> +        }
If you have a flat fee token policy, wouldn't you always want the flat fee and not a percentage of the amount?

2022-11-04 08:29 UTC, trayanm commented on contracts/libraries/LibFeeCalculator.sol
> +        }
Good point. Unfortunately I am not sure about the correct behaviour. Moreover - the contracts and the validators does not know what a `flat` fee is. Here the value in `_calculatedFee` is the calculated fee (whether flat or percentage, from the validator or a policy) and we want to use `_calculatedFee` only if it is less than the standard fee.

2022-11-08 10:07 UTC, trayanm commented on contracts/libraries/LibFeeCalculator.sol
> +        }
This check is removed, as it is already done in `RouterFacet.lock(...)` [here](https://github.com/LimeChain/hashport-contracts/blob/2e490cb43aa957e5c3d3556a51424d5732cddd9b/contracts/facets/RouterFacet.sol#L70)
The change will affect the logic of `unlockWithFee(...)` as - we are using the calculated fee **`as is`** calculated by the validators.

2022-11-08 10:58 UTC, svetlio8 approved these changes

2022-11-08 11:00 UTC, trayanm commented on contracts/EntityFeePolicyStore.sol
> +pragma solidity 0.8.3;
The current version of solidity will not break the compatibility. We will change the version in later state.

2022-11-09 10:08 UTC, failfmi commented on contracts/facets/RouterFacet.sol
> +        require(serviceFee == _serviceFee, "RouterFacet: Service fee mismatch");
Test for this is missing

2022-11-09 10:13 UTC, failfmi commented
When you execute `npx hardhat coverage`, there are failing tests

2022-11-09 10:38 UTC, failfmi commented on abi/ReplaceFacet.json
> +]
This is not removed

2022-11-09 11:15 UTC, failfmi commented on test/router.js
> +        const _hashData = ethers.utils.arrayify(hashMsg);
What's the difference between these two tests?

2022-11-09 11:24 UTC, failfmi commented on test/router.js
> +        const expectedFee = amount.mul(FEE_CALCULATOR_TOKEN_SERVICE_FEE).div(FEE_CALCULATOR_PRECISION);
nit: unused

2022-11-09 11:24 UTC, failfmi commented on test/router.js
> +          expect(beforeMemberUpdateTokenFeeData.previousAccrued).to.equal(0);
Could you assert the router's balance as well?

2022-11-11 12:18 UTC, Daniel-K-Ivanov requested changes
Good work! I've added some comments, mostly nits / cosmetic suggestions and typos.

2022-11-11 12:18 UTC, Daniel-K-Ivanov commented on contracts/policies/FlatFeePerTokenPolicy.sol
> +    mapping(address => uint256) pairs;
nit: I think that a better name for the mapping would be `fees` or `tokenFees`

2022-11-11 12:18 UTC, Daniel-K-Ivanov commented on contracts/policies/FlatFeePerTokenPolicy.sol
> +    function getFlatFee(address _tokenAddress) external view returns (uint256) {
nit: Solidity auto generartes getter for public mappings. I would advise 1) renaming the `pairs` mapping; 2) making it public; 3) removing `getFlatFee` function.

Result:
users would be able to query `tokenFees` / `fees` by doing `.tokenFees(token)` or `.fees(token)`

2022-11-11 12:18 UTC, Daniel-K-Ivanov commented on contracts/policies/FlatFeePolicy.sol
> +    uint256 flatFee;
Lets make this variable public so that solidity auto generates a getter and remove the `getFlatFee`

2022-11-11 12:18 UTC, Daniel-K-Ivanov commented on contracts/policies/PercentageFeePolicy.sol
> +    uint256 feePercentage;
same comments for public variables, autogenerating getters and removal of explicit getters in the code

2022-11-11 12:18 UTC, Daniel-K-Ivanov commented on scripts/fee-policy-management.js
> +async function upgradeRouter(routerAddress, routerFacetAddress, feeCalculatorFacetAddress) {
nit: Lets rename the file to `fee-policy-management-upgrade`. I think that it would be more explicit stating that this script is for upgrading the router to support fee policy management

2022-11-11 12:18 UTC, Daniel-K-Ivanov commented on contracts/facets/FeePolicyFacet.sol
> +    /// @dev To remove IFeePolicy from user users - pass _feePolicyAddress as zero addres.
```suggestion
    /// @dev To remove IFeePolicy from user users - pass _feePolicyAddress as zero address.
```

2022-11-11 12:59 UTC, rokn commented on contracts/interfaces/IRouter.sol
> +    ) external;
nit: whitespace

2022-11-14 07:08 UTC, failfmi commented on contracts/interfaces/IFeePolicy.sol
> +    /// @return exist Flag describing if a fee polocy for the given parameters is found and calculated.
nit: typo

2022-11-14 07:15 UTC, failfmi approved these changes

2022-11-14 07:15 UTC, failfmi commented on test/router.js
> +      // expect(ownerAddress).to.equal(router.address);
Could we revert this?

2022-11-14 07:52 UTC, trayanm commented on contracts/facets/RouterFacet.sol
>      function lock(
As the signature of function `lock(..)` is changed - amendment in all clients using this function are required. The flow should be:
1) call `router.feeAmountFor(...)` (function defined in FeeCalculatorFacet)
2) call function `lock(...)` with new signature and pass the result from 1. to param `_serviceFee`

2022-11-14 10:34 UTC, rokn approved these changes

2022-11-14 15:28 UTC, svetlio8 approved these changes

2022-11-15 15:08 UTC, Daniel-K-Ivanov approved these changes

2022-11-15 15:24 UTC, merged